"""add_followup_tables

Revision ID: a7e0fbf6d586
Revises: 9bd4c7d34995
Create Date: 2026-01-04 14:57:40.679648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e0fbf6d586'
down_revision: Union[str, None] = '9bd4c7d34995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_followups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('followup_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_followups_scheduled_at'), 'scheduled_followups', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduled_followups_status'), 'scheduled_followups', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_followups_user_id'), 'scheduled_followups', ['user_id'], unique=False)
    op.create_table('user_engagements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_followup_sent_at', sa.DateTime(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('preferred_time_hour', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_minutes', sa.Integer(), nullable=True),
    sa.Column('has_active_plan', sa.Boolean(), nullable=True),
    sa.Column('plan_start_date', sa.DateTime(), nullable=True),
    sa.Column('current_goals', sa.Text(), nullable=True),
    sa.Column('followup_enabled', sa.Boolean(), nullable=True),
    sa.Column('followup_frequency_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_engagements')
    op.drop_index(op.f('ix_scheduled_followups_user_id'), table_name='scheduled_followups')
    op.drop_index(op.f('ix_scheduled_followups_status'), table_name='scheduled_followups')
    op.drop_index(op.f('ix_scheduled_followups_scheduled_at'), table_name='scheduled_followups')
    op.drop_table('scheduled_followups')
    # ### end Alembic commands ###
