"""add_user_profiles_table

Revision ID: f3609d0174d4
Revises: a7e0fbf6d586
Create Date: 2026-01-04 22:54:24.541556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3609d0174d4'
down_revision: Union[str, None] = 'a7e0fbf6d586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('onboarding_stage', sa.String(length=50), nullable=True),
    sa.Column('onboarding_started_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('questions_asked', sa.JSON(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('primary_goal', sa.String(length=50), nullable=True),
    sa.Column('secondary_goals', sa.JSON(), nullable=True),
    sa.Column('goal_timeline', sa.String(length=50), nullable=True),
    sa.Column('goal_motivation', sa.Text(), nullable=True),
    sa.Column('previous_attempts', sa.Text(), nullable=True),
    sa.Column('work_hours_per_day', sa.Integer(), nullable=True),
    sa.Column('work_schedule', sa.String(length=50), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.String(length=20), nullable=True),
    sa.Column('sleep_time', sa.String(length=20), nullable=True),
    sa.Column('wake_time', sa.String(length=20), nullable=True),
    sa.Column('stress_level', sa.String(length=20), nullable=True),
    sa.Column('stress_triggers', sa.Text(), nullable=True),
    sa.Column('diet_type', sa.String(length=30), nullable=True),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('breakfast_habit', sa.String(length=20), nullable=True),
    sa.Column('cooking_frequency', sa.String(length=20), nullable=True),
    sa.Column('eating_out_frequency', sa.String(length=20), nullable=True),
    sa.Column('water_intake_liters', sa.Float(), nullable=True),
    sa.Column('snacking_habit', sa.String(length=20), nullable=True),
    sa.Column('food_allergies', sa.JSON(), nullable=True),
    sa.Column('food_dislikes', sa.JSON(), nullable=True),
    sa.Column('activity_level', sa.String(length=30), nullable=True),
    sa.Column('current_exercise', sa.Text(), nullable=True),
    sa.Column('exercise_frequency', sa.String(length=20), nullable=True),
    sa.Column('preferred_exercise', sa.JSON(), nullable=True),
    sa.Column('physical_limitations', sa.Text(), nullable=True),
    sa.Column('has_gym_access', sa.Boolean(), nullable=True),
    sa.Column('medical_conditions', sa.JSON(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('supplements', sa.JSON(), nullable=True),
    sa.Column('family_health_history', sa.Text(), nullable=True),
    sa.Column('recent_health_checkup', sa.Boolean(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('preferred_contact_time', sa.String(length=20), nullable=True),
    sa.Column('motivation_style', sa.String(length=30), nullable=True),
    sa.Column('budget_constraints', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
